############################################################################
# configure toolchain
############################################################################
bazel_dep(name = "rules_shell", version = "0.6.1", dev_dependency = True)
bazel_dep(name = "bazel_skylib", version = "1.9.2", dev_dependency = True)
bazel_dep(name = "googletest", version = "1.17.0", dev_dependency = True)
bazel_dep(name = "toolchains_llvm", version = "1.6.0", dev_dependency = True)
bazel_dep(name = "platforms", version = "1.0.0", dev_dependency = True)
bazel_dep(name = "rules_build_error", version = "0.11.0", dev_dependency = True)

llvm = use_extension("@toolchains_llvm//toolchain/extensions:llvm.bzl", "llvm", dev_dependency = True)
llvm.toolchain(
    name = "llvm_toolchain",
    cxx_standard = {"": "c++23"},
    llvm_versions = {
        "": "21.1.6",
    },
)
use_repo(llvm, "llvm_toolchain", "llvm_toolchain_llvm")

register_toolchains(
    "@llvm_toolchain//:all",
    dev_dependency = True,
)

############################################################################
# configure linters
############################################################################
bazel_dep(name = "aspect_rules_lint", version = "2.7.2", dev_dependency = True)

# C++ linter tools
lint_tools = use_extension("@aspect_rules_lint//lint:extensions.bzl", "tools", dev_dependency = True)
lint_tools.cppcheck()
use_repo(
    lint_tools,
    "cppcheck_linux",
    "cppcheck_macos",
)

bazel_dep(name = "bazel_lib", version = "3.0.0", dev_dependency = True)
bazel_dep(name = "buildifier_prebuilt", version = "8.5.1.4", dev_dependency = True)

############################################################################
# configure hedron plugin
############################################################################
bazel_dep(name = "rules_python", version = "1.8.1", dev_dependency = True)

python = use_extension("@rules_python//python/extensions:python.bzl", "python", dev_dependency = True)
python.toolchain(
    # TODO: remove this when `ignore_root_user_error` is hermetic
    # https://github.com/bazelbuild/rules_python/issues/2016
    ignore_root_user_error = True,
    python_version = "3.10",
)
python.toolchain(
    ignore_root_user_error = True,
    python_version = "3.12",
)

bazel_dep(name = "hedron_compile_commands", dev_dependency = True)
git_override(
    module_name = "hedron_compile_commands",
    remote = "https://github.com/helly25/bazel-compile-commands-extractor.git",
    commit = "0e990032f3c5a866e72615cf67e5ce22186dcb97",
)
