name: Tests


on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review

# Cancel previous runs for the same branch or pull request automatically
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  tests:
    name: Build, Test, lint and Format
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false

    steps:
      - uses: actions/checkout@v7
      - name: Install Linux Packages
        run: |
          sudo apt-get update
          sudo apt-get install -y libudev-dev
      - uses: bazel-contrib/setup-bazel@0.19.0
        with:
          # Avoid downloading Bazel every time.
          bazelisk-cache: true
          # Store build cache per workflow.
          disk-cache: ${{ github.workflow }}
          # Share repository cache between workflows.
          repository-cache: true
          bazelrc: |
            common --color=yes
            common --show_timestamps
            common --show_progress_rate_limit=-1
            common --config=remote-cache

      # TODO(34): run integraiton tests only if the physical device is present
      - name: hidapi-cpp - Test, lint and format
        env:
          BUILDBUDDY_API_KEY: ${{ secrets.BUILDBUDDY_API_KEY }}
        run: |
          cd third-party/hidapi-cpp
          bazel test -- //... -//tests/integration/... 
          bazel run //tools/format:format.check

      - name: ratbag-cpp - Test, lint and format
        env:
          BUILDBUDDY_API_KEY: ${{ secrets.BUILDBUDDY_API_KEY }}
        run: |
          bazel test //...
          bazel run //tools/format:format.check
