name: Tests
 
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test-and-lint:
    name: Build & Run Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7
      - uses: bazel-contrib/setup-bazel@0.19.0
        with:
          # Avoid downloading Bazel every time.
          bazelisk-cache: true
          # Store build cache per workflow.
          disk-cache: ${{ github.workflow }}
          # Share repository cache between workflows.
          repository-cache: true
          bazelrc: |
            build --color=yes
            build --show_timestamps

      - name: Build
        run: |
          bazel build --config=lint //...
          cd third-party/hidapi-cpp && bazel build --config=lint --output_groups=rules_lint_human //...

      - name: Test & lint
        run: |
          bazel test //...
          cd third-party/hidapi-cpp && bazel test //... 

      - name: Format check
        run: |
          bazel run //tools/format:format.check 
